### ISSUE TITLE
Plugin Ideas

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/integrations-repository#9]
An issue for all plugin ideas that come up. There are no bad ideas!

## List

- [x] PostHog/plugin-repository#11: Postgres
- [x] PostHog/plugin-repository#12: S3
- [x] PostHog/plugin-repository#13: Snowflake
- [ ] Export plugins for all data warehouses
- [ ] Security monitoring: e.g. emit a warning event if some property on an event matches a given pattern
- [ ] Payment processor plugins
- [ ] User aggregator plugin: create new users that are a combination of users based on a certain pattern (e.g. for organization-based analytics)
